plugins { id 'java'; id 'application' }
group = 'ru.vyatsu.ita'; version = '1.0'
application { mainClass = 'ru.vyatsu.ita.lab12.App' }
dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.46.1.0'
    implementation 'org.slf4j:slf4j-simple:2.0.13'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
