package ru.vyatsu.ita.lab12.ui;
import ru.vyatsu.ita.lab12.model.*; import ru.vyatsu.ita.lab12.service.*; import javax.swing.*; import javax.swing.table.*; import java.awt.*;
public final class MainFrame extends JFrame {private final LabService service;private final DefaultListModel<Project> projects=new DefaultListModel<>();private final JList<Project> projectList=new JList<>(projects);private final DefaultTableModel runs=new DefaultTableModel(new String[]{"ID","Статус","Начало","LLM"},0);private final DefaultTableModel tests=new DefaultTableModel(new String[]{"ID","Метод","Тип","Название","Ожидается","Источник"},0);
 public MainFrame(LabService s){super("IntelligentTestAgent — CASE-приложение");service=s;setDefaultCloseOperation(EXIT_ON_CLOSE);setSize(1050,650);setLocationRelativeTo(null);build();refreshProjects();}
 private void build(){var tabs=new JTabbedPane();tabs.add("Запуски анализа",new JScrollPane(new JTable(runs)));tabs.add("Тест-кейсы",new JScrollPane(new JTable(tests)));projectList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);projectList.addListSelectionListener(e->{if(!e.getValueIsAdjusting())refreshDetails();});var left=new JPanel(new BorderLayout());left.setBorder(BorderFactory.createTitledBorder("Проекты анализа"));left.add(new JScrollPane(projectList));var add=new JButton("Добавить проект");add.addActionListener(e->addProject());left.add(add,BorderLayout.SOUTH);var split=new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,left,tabs);split.setDividerLocation(260);add(split);var south=new JPanel();var tc=new JButton("Добавить тест-кейс");tc.addActionListener(e->addTest());var refresh=new JButton("Обновить");refresh.addActionListener(e->{refreshProjects();refreshDetails();});south.add(tc);south.add(refresh);add(south,BorderLayout.SOUTH);}
 private void refreshProjects(){try{projects.clear();service.projects().forEach(projects::addElement);if(!projects.isEmpty())projectList.setSelectedIndex(0);}catch(Exception e){error(e);}}
 private void refreshDetails(){runs.setRowCount(0);tests.setRowCount(0);var p=projectList.getSelectedValue();if(p==null)return;try{for(var r:service.runs(p.id()))runs.addRow(new Object[]{r.id(),r.status(),r.startedAt(),r.llmModel()});for(var t:service.tests(p.id()))tests.addRow(new Object[]{t.id(),t.methodId(),t.type(),t.title(),t.expectedResult(),t.generatedBy()});}catch(Exception e){error(e);}}
 private void addProject(){var name=JOptionPane.showInputDialog(this,"Название проекта");if(name==null)return;var path=JOptionPane.showInputDialog(this,"Путь к исходникам","src/main/java");if(path==null)return;try{service.addProject(name,path);refreshProjects();}catch(Exception e){error(e);}}
 private void addTest(){var p=projectList.getSelectedValue();if(p==null)return;var method=JOptionPane.showInputDialog(this,"ID метода");var title=JOptionPane.showInputDialog(this,"Название тест-кейса");if(method==null||title==null)return;try{service.addTestCase(Long.parseLong(method),"POSITIVE",title,"успешное выполнение");refreshDetails();}catch(Exception e){error(e);}}
 private void error(Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),"Ошибка",JOptionPane.ERROR_MESSAGE);}
}
