@startsalt window-mockup
' Макет главного окна (составлен до реализации, PlantUML Salt)
{+
  <b>Журнал запусков генерации тестов
  {^"Фильтр запусков"
    Проект: | ^Все проекты^ | Покрытие от, %: | "0  " | до, %: | "100" | [X] Только с непокрытыми ветвями | [Применить] | [Сбросить] | [Обновить]
  }
  {
    {^"Запуски генерации тестов"
      {#
        Проект | Начало | Статус | Функций | Тест-кейсов | Ветви | Покрытие
        OrderProcessor | 01.07.2026 13:00 | Завершён | 5 | 68 | 41 / 41 | 100,0 %
        SampleCalculator | 01.07.2026 14:00 | Завершён | 2 | 14 | 7 / 7 | 100,0 %
      }
    }
    {^"Детали выбранного запуска"
      Запуск: OrderProcessor, покрытие ветвей 100,0 % | [Добавить заметку] | [Удалить запуск]
      {/ <b>Функции | Ветви | Тест-кейсы | Заметки }
      {#
        Класс | Функция | Сложность | Ветви | Покрытие
        OrderProcessor | calculateDiscount | 7 | 12 / 12 | 100,0 %
        OrderProcessor | validateOrder | 4 | 6 / 6 | 100,0 %
      }
    }
  } | {^"Сводка по выборке"
    Запусков: 3
    Среднее покрытие: 100,0 %
    Тест-кейсов: 92
    Непокрытых ветвей: 0
    <b>Самые сложные функции
    {#
      Функция | Сложн.
      calculateDiscount | 7
      processInventory | 7
    }
  }
}
@endsalt
